### ISSUE TITLE
Import from ReCiter into ReCiterDB fails probably because of null email for _dar7342

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter-MachineLearning-Analysis#16]
Workflow should be able to anticipate null emails.

![2351b94f-59ee-471d-96ad-97f751933ab4](https://user-images.githubusercontent.com/3651640/150158159-f0a5c3cc-d02b-4a1e-8ee8-e8685baef7f8.jpg)

![09c02845-9954-4709-8f3c-f9c40262dac7](https://user-images.githubusercontent.com/3651640/150158177-50665f0f-873b-4bc2-9a0a-4b250aa6d32e.jpg)

**Comment by sarbajitdutta** [comment]
Fixed had to increase articleTitle and journal length in database - https://github.com/wcmc-its/ReCiter-MachineLearning-Analysis/commit/f8a536b1c78078c0476d886ec3adcffac5ab8961
